services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_PORT=587
      - SPRING_RABBITMQ_STREAM_USERNAME=izzatbek
      - SPRING_RABBITMQ_STREAM_PASSWORD=izzatbek
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
  app:
    build: .
    container_name: demo-app
    restart: always
    environment:
      - SPRING_MAIL_SMTP_HOST=smtp.gmail.container_name
      - SPRING_MAIL_SMTP_PORT=587
      - SPRING_MAIL_SMTP_USERNAME=your-email@gmail.com
      - SPRING_MAIL_SMTP_PASSWORD=your-app-password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_STREAM_USERNAME=izzatbek
      - SPRING_RABBITMQ_STREAM_PASSWORD=izzatbek
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data: {}
