spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    stream:
      username: ${SPRING_RABBITMQ_STREAM_USERNAME}
      password: ${SPRING_RABBITMQ_STREAM_PASSWORD}
  mail:
    host: ${SPRING_MAIL_SMTP_HOST}
    port: ${SPRING_MAIL_SMTP_PORT}
    username: ${SPRING_MAIL_SMTP_USERNAME}
    password: ${SPRING_MAIL_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true