spring:
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: izzatbek
      password: izzatbek
  mail:
    host: smtp.gmail.com
    port: 587
    username: abdusharipovizzat03@gmail.com
    password: "imqxgmknlitptslp"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true